version: "2"

services:

  prometheus:
    image: "prometheus:latest"
    container_name: prometheus
    links:
      - "alertmanager:alertmanager"
    ports:
      - "3000:3000"
      - "9090:9090"
    depends_on:
      - alertmanager

  alertmanager:
    image: "alertmanager:latest"
    container_name: alertmanager
    ports:
      - "9093:9093"
